#Test with: http://editor.swagger.io/

swagger: '2.0'
info:
  version: 1.0.0
  title: Microservice for sessions manage
  description: Java Srpring boot + MySQL
  license:
    name: Software Architecture, 2020-I
host: localhost:4000
basePath: /schedule
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /new-schedule:
    post:
      summary: Creates a new schedule
      operationId: registerNewSchedule
      parameters:
        - name: schedule
          in: body
          required: true
          description: RegisterSchedulePOJO Object
          schema:
            $ref: '#/definitions/ScheduleInput'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorModel'
    
  /get-by-idCoach/{idCoach}:
    get:
      summary: Returns the list of schedule of the coach with the given id
      operationId: getUserById
      parameters:
        - name: idCoach
          in: path
          description: The id of the coach 
          required: true
          type: integer
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/Schedule'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorModel'
        '406':
            description: Not Acceptable (Invalid Params)
            schema:
              $ref: '#/definitions/ErrorModel'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'

  /get-by-idCoach/Current/{idCoach}:
    get:
      summary: Returns the list of current schedule of the coach with the given id
      operationId: getUserById
      parameters:
        - name: idCoach
          in: path
          description: The id of the coach 
          required: true
          type: integer
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/Schedule'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorModel'
        '406':
            description: Not Acceptable (Invalid Params)
            schema:
              $ref: '#/definitions/ErrorModel'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'

  /get-by-idUser/{idUser}: 
    get:
      summary: Returns the list of schedule of the user with the given id
      operationId: getUserById
      parameters:
        - name: idUser
          in: path
          description: The id of the user 
          required: true
          type: integer
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/Schedule'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorModel'
        '406':
            description: Not Acceptable (Invalid Params)
            schema:
              $ref: '#/definitions/ErrorModel'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
  /get-by-idUser/Current/{idUser}:
    get:
      summary: Returns the list of current schedule of the user with the given id
      operationId: getUserById
      parameters:
        - name: idUser
          in: path
          description: The id of the user 
          required: true
          type: integer
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/Schedule'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorModel'
        '406':
            description: Not Acceptable (Invalid Params)
            schema:
              $ref: '#/definitions/ErrorModel'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
  

definitions:

  # Users
  Schedule:
    type: object
    properties:
      
      id_schedule:
        type: integer
      idCoach:
        type: integer
      daySession:
        type: yyyy-mm-dd
      iniTime:
        type: hh:mm:ss
      endTime:
        type: hh:mm:ss
      status:
        schema:
            $ref: '#/definitions/Status'
      idUser:
        type: integer

  Status:
    id:
      type: integer
    nameStatus:
      type: string

  ScheduleInput:
    type: object
    properties:
      idCoach:
        type: integer
      daySession:
        type: yyyy-mm-dd
      iniTime:
        type: hh:mm:ss
      endTime:
        type: hh:mm:ss

  UsersList:
    type: object
    required:
      - total
      - list
    properties:
      total:
        type: number
      list:
        type: array
        items:
          $ref: '#/definitions/User'

# Errors
  ErrorModel:
    type: object
    required:
      - message
      - code
    properties:
      message:
        type: string
      code:
        type: number
      description:
        type: object
